### ISSUE TITLE
Touch event works on Chrome, but not on Safari or Firefox

### ISSUE THREAD

**Issue by matthova** [duxiaofeng-github/preact-responder-event-plugin#4]
Not sure what behavior could be browser-specific but wanted to file the behavior 🤷‍♂

**Comment by duxiaofeng-github** [comment]
well, i'll look into it when i'm free

**Comment by duxiaofeng-github** [comment]
@matthova sorry for pending so long, finally i fix this. it caused by a small compatible issue. you can upgrade to 1.0.16 and try it now
